api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

# Don't know why it don't work
#    mapping:
#        paths:
#            - '%kernel.project_dir%/config/api_platform'
#    patch_formats:
#        json: [ 'application/merge-patch+json' ]
#    formats:
#        json:
#            mime_types: [ 'application/json' ]
#        jsonld:
#            mime_types: [ 'application/ld+json' ]
#        multipart:
#            mime_types: [ 'multipart/form-data' ]
#    swagger:
#        versions: [ 3 ]
#        api_keys:
#            -   name: Authorization
#                type: header
#    allow_plain_identifiers: true
#    name_converter: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
#    path_segment_name_generator: api_platform.path_segment_name_generator.dash
#    exception_to_status:
#        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
#        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
#        ApiPlatform\Core\Exception\FilterValidationException: 400
#        Doctrine\ORM\OptimisticLockException: 409
#
#        App\Exception\UploadedFileInvalidException: 400
#        App\Service\Integration\IntegrationException: 400
#    collection:
#        pagination:
#            items_per_page: 25
