version: '3.7'

networks:
    default:
        name: rpbook-docker-network

services:
    mongo:
        image: library/mongo:4.4.3
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        volumes:
            - './docker/mongo/db:/data/db'
        ports:
            - '27018:27017'

    mysql:
        image: library/mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
        volumes:
            - './docker/mysql/db:/var/lib/mysql'
        # Steps to recover from downgrading:
        #  sudo docker ps -a   - look for mysql, note container id
        #  sudo docker inspect <CONTAINER>  - look for "Mount" / "Name" - note volume Id
        #  sudo docker rm <CONTAINER>
        #  sudo docker volume rm <VOLUME>
        ports:
            - '3307:3306'

    nginx:
        image: library/nginx:1.19-alpine
        volumes:
            - './public:/usr/src/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'
        depends_on:
            - php

    nginx_phpunit:
        image: library/nginx:1.19-alpine
        volumes:
            - './public:/usr/src/app'
            - './docker/nginx_phpunit/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8089:80'
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        env_file:
            - .env
        environment:
            APP_DEBUG: 1,
            API_BASE_URI: "http://nginx"
            MONGODB_URL: "mongodb://mongo:27017"
            DATABASE_URL: "mysql://db_user:db_password@mysql:3306/db_name?serverVersion=mariadb-10.3.22"
        volumes:
            - './:/usr/src/app'
        user: 1000:1000

    phpunit:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        env_file:
            - .env
        environment:
            API_BASE_URI: "http://nginx_phpunit"
            MONGODB_URL: "mongodb://mongo:27017"
            MONGODB_DB: "symfony_phpunit"
            DATABASE_URL: "mysql://root:root@mysql:3306/db_name_phpunit?serverVersion=mariadb-10.3.22"
        volumes:
            - './:/usr/src/app'
        user: 1000:1000
