monolog:
    channels:
        - 'tests'
        - 'imports'
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        tests:
            level: info
            type: stream
            path: '%kernel.logs_dir%/tests.log'
            channels: [ 'tests' ]
        imports:
            level: info
            type: stream
            path: '%kernel.logs_dir%/imports.log'
            channels: [ 'imports' ]
